CREATE DOMAIN IF NOT EXISTS rol_usuario AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS estado_habitacion AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS estado_reserva AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS estado_bloqueo AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS gravedad_averia AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS estado_averia AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS tipo_tarea_limpieza AS VARCHAR(50);