# Configuración del DataSource JDBC usando variables de entorno
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# seed data para el jefe (para evitar valores hardcodeados rellenr en .env)
app.jefe.username=${JEFE_USERNAME:jefe}
app.jefe.email=${JEFE_EMAIL:jefe@hotel.com}
app.jefe.password=${JEFE_PASSWORD:Admin123}